# Site settings
title: "ディープラーニングの心理学的解釈"
baseurl: ""
url: "http://komazawa-deeplearning.github.io/2021"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: minima
#theme: jekyll-theme-cayman 
#remote-theme: minimal-mistakes-jekyll
#remote_theme: "mmistakes/minimal-mistakes@4.22.0"
port: 4005
